### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mtbsteve** [thomasesmith/php-vw-car-net#2]
Thomas, I tried to install your wrapper using composer as you explained in the wiki. I am getting the following errors:
```
$ composer require thomasesmith/php-vw-car-net
Using version ^0.2.2 for thomasesmith/php-vw-car-net
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for thomasesmith/php-vw-car-net ^0.2.2 -> satisfiable by thomasesmith/php-vw-car-net[v0.2.2].
    - thomasesmith/php-vw-car-net v0.2.2 requires ext-simplexml * -> the requested PHP extension simplexml is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.
```
How can I fix this (I am not a php expert)
Thx Stephan

**Comment by thomasesmith** [comment]
Hey. It looks like your machine doesn't have the required PHP extension "simplexml" installed. This package relies on that extension to be installed before it can run. 

It's difficult for me to give you specific advice on how to install it because it would require me knowing more about your machine, but SimpleXML is a very popular extension so it shouldn't be too tough to find on the web information on how to install it, for your specific case. It might even be installed, but disabled in one of the .ini config files listed there. 

I would search the web for "installing php simplexml extension [your machines operating system and version]" or if this is a server thats hosted by a hosting company, maybe something "enabling php simplexml extension [host company name]" for more information on how to get this installed.

**Comment by mtbsteve** [comment]
Thanks for the hint!
Just for the records for Ubuntu 18.04 run the following commands:
```
sudo apt-get update -y
sudo apt-get install -y php-simplexml

```

**Comment by thomasesmith** [comment]
I'm glad you figured this out! Thank you for closing.
